platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'

platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'

platform :ios, '7.0'
pod 'Toast', '~> 3.0'

pod 'MJRefresh'

platform :ios, '7.0'
pod 'MBProgressHUD', '~> 0.9.2'